sudo: required
dist: trusty

language: scala

addons:
  firefox: latest
  chrome: stable

before_script:
  # Install google-chrome-driver
  - wget http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PWD/chromedriver:$PATH
  # Install firefox-driver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PWD/geckodriver:$PATH

script:
  - xvfb-run sbt ++$TRAVIS_SCALA_VERSION $TEST_PACKAGE

jdk:
  - oraclejdk8
scala:
  - 2.11.12
  - 2.12.7

env:
  - TEST_PACKAGE="utils/test utils-js/test"
  - TEST_PACKAGE="core/test core-js/test"
  - TEST_PACKAGE="rpc/test rpc-js/test"
  - TEST_PACKAGE="rest/test rest-js/test"
  - TEST_PACKAGE="i18n/test i18n-js/test"
  - TEST_PACKAGE="auth/test auth-js/test"
  - TEST_PACKAGE="css/test css-js/test"
  - TEST_PACKAGE="bootstrap/test"
  - TEST_PACKAGE="bootstrap4/test"
  - TEST_PACKAGE="charts/test"
  - TEST_PACKAGE="benchmarks/compile"
  - TEST_PACKAGE="selenium/test"

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.coursier/cache
  - $HOME/.sbt/boot/
  - $HOME/.sbt/launchers/
