sudo: required
dist: trusty

language: scala

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # Instal google-chrome
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  # Install Selenium chromedriver
  - wget http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d selenium-bin
  - export PATH=$PWD/selenium-bin:$PATH

script:
  - sbt ++$TRAVIS_SCALA_VERSION $TEST_PACKAGE

jdk:
  - oraclejdk8

scala:
  - 2.11.12
  - 2.12.6

env:
  - TEST_PACKAGE="core-macros/test core-shared/test core-shared-JS/test core-frontend/test"
  - TEST_PACKAGE="rpc-shared/test rpc-shared-JS/test rpc-backend/test rpc-frontend/test"
  - TEST_PACKAGE="rest-macros/test rest-shared/test rest-shared-JS/test rest-backend/test"
  - TEST_PACKAGE="i18n-shared/test i18n-shared-JS/test i18n-backend/test i18n-frontend/test"
  - TEST_PACKAGE="auth-shared/test auth-shared-JS/test auth-frontend/test"
  - TEST_PACKAGE="css-macros/test css-shared/test css-shared-JS/test css-backend/test css-frontend/test"
  - TEST_PACKAGE="bootstrap/test"
  - TEST_PACKAGE="charts/test"
  - TEST_PACKAGE="benchmarks-frontend/compile"
  - TEST_PACKAGE="selenium-backend/test"